package scanner

import (
	"path/filepath"
	"testing"

	"github.com/ClauGuard/clauguard/pkg/models"
)

func TestCargoParser_Ecosystem(t *testing.T) {
	p := &CargoParser{}
	if p.Ecosystem() != models.EcosystemCargo {
		t.Errorf("expected cargo, got %s", p.Ecosystem())
	}
}

func TestCargoParser_CargoToml_DepsAndDevDeps(t *testing.T) {
	dir := t.TempDir()
	content := `[package]
name = "myproject"
version = "0.1.0"

[dependencies]
serde = "1.0"
tokio = { version = "1.34", features = ["full"] }

[dev-dependencies]
criterion = "0.5"
`
	writeTempFile(t, dir, "Cargo.toml", content)

	p := &CargoParser{}
	deps, err := p.Parse(filepath.Join(dir, "Cargo.toml"))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(deps) != 3 {
		t.Fatalf("expected 3 deps, got %d", len(deps))
	}

	depMap := map[string]models.Dependency{}
	for _, d := range deps {
		depMap[d.Name] = d
	}

	// Simple string version
	if depMap["serde"].Version != "1.0" {
		t.Errorf("expected 1.0, got %s", depMap["serde"].Version)
	}

	// Inline table version extraction
	if depMap["tokio"].Version != "1.34" {
		t.Errorf("expected 1.34, got %s", depMap["tokio"].Version)
	}
	if depMap["tokio"].IsDev {
		t.Error("tokio should not be dev")
	}

	// Dev dependency
	if !depMap["criterion"].IsDev {
		t.Error("criterion should be dev")
	}
}

func TestCargoParser_CargoToml_DevUnderscoreDependencies(t *testing.T) {
	dir := t.TempDir()
	content := `[package]
name = "myproject"
version = "0.1.0"

[dev_dependencies]
mockall = "0.11"
`
	writeTempFile(t, dir, "Cargo.toml", content)

	p := &CargoParser{}
	deps, err := p.Parse(filepath.Join(dir, "Cargo.toml"))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(deps) != 1 {
		t.Fatalf("expected 1 dep, got %d", len(deps))
	}
	if !deps[0].IsDev {
		t.Error("expected dev_dependencies to be marked as dev")
	}
}

func TestCargoParser_CargoToml_SectionBoundary(t *testing.T) {
	dir := t.TempDir()
	content := `[dependencies]
serde = "1.0"

[build-dependencies]
cc = "1.0"

[dev-dependencies]
test-log = "0.2"
`
	writeTempFile(t, dir, "Cargo.toml", content)

	p := &CargoParser{}
	deps, err := p.Parse(filepath.Join(dir, "Cargo.toml"))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	// [build-dependencies] is a new [section], so parsing stops for deps
	// then [dev-dependencies] starts a new recognized section
	if len(deps) != 2 {
		t.Fatalf("expected 2 deps (serde + test-log), got %d", len(deps))
	}

	depMap := map[string]models.Dependency{}
	for _, d := range deps {
		depMap[d.Name] = d
	}

	if _, ok := depMap["cc"]; ok {
		t.Error("build-dependencies should not be parsed as deps or dev-deps")
	}
}

func TestCargoParser_CargoLock_MultiplePackages(t *testing.T) {
	dir := t.TempDir()
	content := `# This file is automatically @generated by Cargo.
[[package]]
name = "serde"
version = "1.0.193"

[[package]]
name = "tokio"
version = "1.34.0"

[[package]]
name = "libc"
version = "0.2.150"
`
	writeTempFile(t, dir, "Cargo.lock", content)

	p := &CargoParser{}
	deps, err := p.Parse(filepath.Join(dir, "Cargo.lock"))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(deps) != 3 {
		t.Fatalf("expected 3 deps, got %d", len(deps))
	}

	depMap := map[string]models.Dependency{}
	for _, d := range deps {
		depMap[d.Name] = d
	}

	if depMap["serde"].Version != "1.0.193" {
		t.Errorf("expected 1.0.193, got %s", depMap["serde"].Version)
	}
	if depMap["tokio"].Version != "1.34.0" {
		t.Errorf("expected 1.34.0, got %s", depMap["tokio"].Version)
	}
	// Last package should not be forgotten
	if depMap["libc"].Version != "0.2.150" {
		t.Errorf("expected 0.2.150, got %s", depMap["libc"].Version)
	}
}

func TestCargoParser_CargoLock_LastPackageNotForgotten(t *testing.T) {
	dir := t.TempDir()
	// Only one package, no trailing [[package]] to flush it
	content := `[[package]]
name = "only-one"
version = "0.1.0"
`
	writeTempFile(t, dir, "Cargo.lock", content)

	p := &CargoParser{}
	deps, err := p.Parse(filepath.Join(dir, "Cargo.lock"))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(deps) != 1 {
		t.Fatalf("expected 1 dep, got %d", len(deps))
	}
	if deps[0].Name != "only-one" {
		t.Errorf("expected only-one, got %s", deps[0].Name)
	}
}

func TestCargoParser_CargoToml_EmptyDeps(t *testing.T) {
	dir := t.TempDir()
	content := `[package]
name = "myproject"
version = "0.1.0"

[dependencies]
`
	writeTempFile(t, dir, "Cargo.toml", content)

	p := &CargoParser{}
	deps, err := p.Parse(filepath.Join(dir, "Cargo.toml"))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(deps) != 0 {
		t.Errorf("expected 0 deps, got %d", len(deps))
	}
}

func TestCargoParser_CargoToml_CommentsIgnored(t *testing.T) {
	dir := t.TempDir()
	content := `[dependencies]
# This is a comment
serde = "1.0"
# Another comment
`
	writeTempFile(t, dir, "Cargo.toml", content)

	p := &CargoParser{}
	deps, err := p.Parse(filepath.Join(dir, "Cargo.toml"))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(deps) != 1 {
		t.Fatalf("expected 1 dep, got %d", len(deps))
	}
}

func TestCargoParser_UnknownFile(t *testing.T) {
	p := &CargoParser{}
	deps, err := p.Parse("/some/random.txt")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if deps != nil {
		t.Errorf("expected nil, got %v", deps)
	}
}

func TestCargoParser_MissingFile(t *testing.T) {
	p := &CargoParser{}
	_, err := p.Parse("/nonexistent/Cargo.toml")
	if err == nil {
		t.Error("expected error for missing file")
	}
}

func TestExtractCargoVersion_SimpleString(t *testing.T) {
	got := extractCargoVersion(`"1.0.5"`)
	if got != "1.0.5" {
		t.Errorf("expected 1.0.5, got %s", got)
	}
}

func TestExtractCargoVersion_InlineTable(t *testing.T) {
	got := extractCargoVersion(`{ version = "1.34", features = ["full"] }`)
	if got != "1.34" {
		t.Errorf("expected 1.34, got %s", got)
	}
}

func TestExtractCargoVersion_InlineTableNoVersion(t *testing.T) {
	got := extractCargoVersion(`{ path = "../other" }`)
	// No version key, returns the raw string
	if got == "" {
		t.Error("expected non-empty fallback")
	}
}

func TestExtractCargoVersion_PlainString(t *testing.T) {
	got := extractCargoVersion("something")
	if got != "something" {
		t.Errorf("expected something, got %s", got)
	}
}
